import Providers from '@/providers/Providers';
import './globals.css';
import { Vazirmatn } from 'next/font/google';
import ThemeRegistry from '@/providers/MUIProvider';

const vazirmatn = Vazirmatn({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        <ThemeRegistry>
          <Providers>{children}</Providers>
        </ThemeRegistry>
      </body>
    </html>
  );
}
